In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

from sklearn.tree import DecisionTreeRegressor

In [18]:
data = pd.read_csv("airbnb-data.csv");

#from the info, reviews per month has a lot of NAN values
data['reviews_per_month'] = data['reviews_per_month'].fillna(0);

#replace all nan values in name with unknown
data['name'] = data['name'].fillna("Unknown");

#drop the id and host_name columns because they aren't really needed here
data.drop(['id', 'host_name'], axis=1, inplace=True);

#removes outliers which will lead to a right skewed distribution
data = data[data['price'] < 500]

data

,name,host_id,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,Clean & quiet apt home by the park,2787,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,Skylit Midtown Castle,2845,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,THE VILLAGE OF HARLEM....NEW YORK !,4632,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,0.00,1,365
3,Cozy Entire Floor of Brownstone,4869,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,Entire Apt: Spacious Studio/Loft by central park,7192,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,Charming one bedroom - newly renovated rowhouse,8232441,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,0.00,2,9
48891,Affordable room in Bushwick/East Williamsburg,6570630,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,0.00,2,36
48892,Sunny Studio at Historical Neighborhood,23492952,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,0.00,1,27
48893,43rd St. Time Square-cozy single bed,30985759,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,0.00,6,2
48894,Trendy duplex in the very heart of Hell's Kitchen,68119814,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,0.00,1,23

In [19]:
data.drop(['host_id', 'name'], axis=1, inplace=True)
data['price'] = np.log1p(data['price'])

In [20]:
#First split, features (x) and target (y)
X = data.drop('price', axis=1) #X is the features of the dataset?

y = data['price']

In [21]:
data.dtypes

neighbourhood_group                   str
neighbourhood                         str
latitude                          float64
longitude                         float64
room_type                             str
price                             float64
minimum_nights                      int64
number_of_reviews                   int64
last_review                           str
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

In [22]:
#convert non-numeric data types
X = pd.get_dummies(X, drop_first=True)
feature_columns = X.columns

In [23]:
X

,latitude,longitude,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,neighbourhood_group_Brooklyn,neighbourhood_group_Manhattan,neighbourhood_group_Queens,...,last_review_2019-06-29,last_review_2019-06-30,last_review_2019-07-01,last_review_2019-07-02,last_review_2019-07-03,last_review_2019-07-04,last_review_2019-07-05,last_review_2019-07-06,last_review_2019-07-07,last_review_2019-07-08
0,40.64749,-73.97237,1,9,0.21,6,365,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,40.75362,-73.98377,1,45,0.38,2,355,False,True,False,...,False,False,False,False,False,False,False,False,False,False
2,40.80902,-73.94190,3,0,0.00,1,365,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,40.68514,-73.95976,1,270,4.64,1,194,True,False,False,...,False,False,False,False,False,False,True,False,False,False
4,40.79851,-73.94399,10,9,0.10,1,0,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,40.67853,-73.94995,2,0,0.00,2,9,True,False,False,...,False,False,False,False,False,False,False,False,False,False
48891,40.70184,-73.93317,4,0,0.00,2,36,True,False,False,...,False,False,False,False,False,False,False,False,False,False
48892,40.81475,-73.94867,10,0,0.00,1,27,False,True,False,...,False,False,False,False,False,False,False,False,False,False
48893,40.75751,-73.99112,1,0,0.00,6,2,False,True,False,...,False,False,False,False,False,False,False,False,False,False
48894,40.76404,-73.98933,7,0,0.00,1,23,False,True,False,...,False,False,False,False,False,False,False,False,False,False

In [24]:
#Train test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [25]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [26]:
model = LinearRegression()
model.fit(X_train, y_train)

pred = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, pred))
print("R2:", r2_score(y_test, pred))

MAE: 0.30863661101483747
R2: 0.5640661504720363

In [ ]:
model = DecisionTreeRegressor()
model.fit(X_train, y_train)

pred = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, pred))
print("R2:", r2_score(y_test, pred))

MAE: 0.36714757754764477
R2: 0.3568992642942591

### Testing the model

In [34]:
latitude = float(input("Enter latitude: "))
longitude = float(input("Enter longitude: "))
minimum_nights = int(input("Minimum nights: "))
number_of_reviews = int(input("Number of reviews: "))
reviews_per_month = float(input("Reviews per month: "))
availability_365 = int(input("Availability in 365 days: "))
room_type = input("Room type (Entire home/apt, Private room, Shared room): ")

user_data = {
    'latitude': latitude,
    'longitude': longitude,
    'minimum_nights': minimum_nights,
    'number_of_reviews': number_of_reviews,
    'reviews_per_month': reviews_per_month,
    'availability_365': availability_365,
    'room_type': room_type
}

In [31]:
user_df = pd.DataFrame([user_data])

user_df = pd.get_dummies(user_df)

user_df = user_df.reindex(columns=feature_columns, fill_value=0)

user_scaled = scaler.transform(user_df)

In [32]:
prediction = model.predict(user_scaled)

final_price = np.expm1(prediction[0])

In [33]:
print("Predicted Airbnb Price:", round(final_price, 2))

Predicted Airbnb Price: 200.0